#!/usr/bin/env php
<?php
// env to debug with MAMP
// #!/Applications//MAMP/bin/php/php5.3.6/bin/php

/*
	Getting Started:
		https://gist.github.com/b038bb8076754968eff5
*/

define("PATH", dirname(__FILE__));
require dirname(__FILE__) . '/libs/hebe.php';

$app = array_shift($argv);
$command = array_shift($argv);
$arguments = $argv;

$file = 'default';
$home = exec('echo $HOME');

if (!$command) $command = 'help';
switch ($command){

	case 'register':
		if (count($arguments) < 1) usage($command);
		$options = array(
			'arguments' => array(),
			'name' => "",
			'force' => false
		);

		$build = 'arguments';

		foreach ($arguments as $arg){

			if ($arg == '+name'){
				$build = 'name';
				continue;
			}

			if ($arg == '+force'){
				$build = 'force';
			}

			if (is_array($options[$build])) $options[$build][] = $arg;
			else if (is_bool($options[$build])) $options[$build] = true;
			else $options[$build] = $arg;

		}

		$hebe = new Hebe();
		$hebe->projects->register($options);

		break;

	case 'unregister':
		if (count($arguments) < 1) usage($command);
		$options = array(
			'arguments' => array()
		);

		$build = 'arguments';

		foreach ($arguments as $arg){

			if (is_array($options[$build])) $options[$build][] = $arg;
			else if (is_bool($options[$build])) $options[$build] = true;
			else $options[$build] = $arg;

		}

		$hebe = new Hebe();
		$hebe->projects->unregister($options);

		break;

	case 'list':
		$selected = array(
			'arguments' => array(),
			'filter' => array(),
			'no_details' => false,
			'no_nodes' => false,
			'no_sources' => false,
			'no_destinations' => false
		);

		$build = 'filter';

		foreach ($arguments as $arg){
			if ($arg == '+filter' || $arg == '+filters'){
				$build = 'filter';
				continue;
			}

			if (is_array($selected[$build])) $selected[$build][] = $arg;
			else if (is_bool($selected[$build])) $selected[$build] = true;
			else $selected[$build] = $arg;

		}

		$hebe = new Hebe();
		$hebe->projects->list_project($selected);

		break;

	case 'link':
		if (count($arguments) < 1) usage($command);
		$selected = array(
			'destinations' => array(),
			'projects' => array(),
			'platform' => "",
			'name'  => "",
			'force' => false
		);

		$build = 'projects';

		foreach ($arguments as $arg){
			if ($arg == '+project' || $arg == '+projects' || $arg == '+proj'){
				$build = 'projects';
				continue;
			}

			if ($arg == '+platforms' || $arg == "+platform" || $arg == '+plat' || $arg == '+p'){
				$build = 'platform';
				continue;
			}

			if ($arg == '+destination' || $arg == '+destinations' || $arg == '+dest' || $arg == '+d'){
				$build = 'destinations';
				continue;
			}

			if ($arg == '+name' || $arg == '+n'){
				$build = 'name';
				continue;
			}

			if ($arg == '+force'){
				$build = 'force';
			}

			if (is_array($selected[$build])) $selected[$build][] = $arg;
			else if (is_bool($selected[$build])) $selected[$build] = true;
			else $selected[$build] = $arg;
		}

		$hebe = new Hebe();
		$hebe->projects->link_project($selected);
		break;

	case 'edit':
		if (count($arguments) < 1) usage($command);
		$selected = array(
			'arguments' => array(),
			'platforms' => array(),
			'force' => false
		);

		$build = 'arguments';

		foreach ($arguments as $arg){
			if ($arg == '+platforms' || $arg == "+platform" || $arg == '+plat' || $arg == '+p'){
				$build = 'platforms';
				continue;
			}
			if ($arg == '+force'){
				$build = 'force';
			}

			if (is_array($selected[$build])) $selected[$build][] = $arg;
			else if (is_bool($selected[$build])) $selected[$build] = true;
			else $selected[$build] = $arg;
		}

		$hebe = new Hebe();
		$hebe->projects->edit_project($selected);
		break;

	case 'sync':
		$selected = array(
			'arguments' => array(),
			'update' => false
		);

		$build = 'arguments';

		foreach ($arguments as $arg){
			if ($arg == '+update' || $arg == '+u'){
				$build = 'update';
			}

			if (is_array($selected[$build])) $selected[$build][] = $arg;
			else if (is_bool($selected[$build])) $selected[$build] = true;
			else $selected[$build] = $arg;
		}

		$hebe = new Hebe();
		$hebe->projects->sync_projects($selected);
		break;


	case 'version': case '--version': case '-v':
		$path = dirname(__FILE__);
		$date = exec("svn info '".$path."' | awk '/^Last Changed Date:/ {print $7,$8,$9,$10,$5}'");
		$version = exec("svn info '".$path."' | grep '^Last Changed Rev:' | sed -e 's/^Last Changed Rev: //'");

		Hebe::message("\nHebe v" . $version . " - ".$date." - RocketTheme\n");

		break;

	case 'update':
		$path = dirname(__FILE__);
		$version = exec("svn info '".$path."' | grep '^Last Changed Rev:' | sed -e 's/^Last Changed Rev: //'");

		Hebe::message("\nUpdating Hebe...");
		Hebe::message(exec("svn update '".$path."'"));
		Hebe::message("\n");

		Hebe::message("Retrieving Updates Log...");
		exec("svn log '".$path."' -r ".$version.":HEAD", $output);
		Hebe::message(implode("\n", $output)."\n");

		break;

	case 'help': case '--help': case '-h': default:
		if ($command == 'help' && count($arguments)) $file = $arguments[0];
		usage($file);
		break;
}

function usage($command = 'default'){
	global $app;

	if (is_array($command)) $command = 'default';
	$dir = dirname(__FILE__);
	$file = $dir."/help/".$command.".txt";

	if (file_exists($file)) Hebe::message(str_replace('%{app}', $app, file_get_contents($file)));
	else Hebe::error("Unable to find the help file `".$file);

	exit(1);
}

?>
